language: php
dist: trusty
sudo: required
group: edge
 
php:
  - 7.4
 
before_script:
  - composer self-update
  - composer install --prefer-source
  - composer require phpunit/phpunit 6.5.5
 
script:
  - vendor/bin/phpunit
